# ==----------------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2024-2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==----------------------------------------------------------------== #

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "A-dependencies"
      - "C-enhancement"
      - "S-needs-triage"
    groups:
      rust-updates:
        update-types: [minor, patch]
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "A-dependencies"
      - "C-enhancement"
      - "S-needs-triage"
    groups:
      pkl-updates:
        update-types: [minor, patch]
