# ==----------------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2024-2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==----------------------------------------------------------------== #

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "1.C- hygiene related"
      - "2.H.PR - hygiene"
      - "3.A - dependencies"
      - "3.A - rust"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "1.C- hygiene related"
      - "2.H.PR - hygiene"
      - "3.A - dependencies"
      - "3.A - github actions / build"
