# ==----------------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2024-2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: Apache-2.0
# ==----------------------------------------------------------------== #

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "area:dependencies"
      - "category:enhancement"
      - "state:needs-triage"
    groups:
      rust-updates:
        update-types: [major, minor, patch]
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "area:dependencies"
      - "category:enhancement"
      - "state:needs-triage"
    groups:
      pkl-updates:
        update-types: [major, minor, patch]
