[package]
name = "necronux"
version = "1.0.0-beta"
authors = ["Nayan (NayanTheSpaceGuy) <nayantsg@proton.me>"]
edition = "2021"
homepage = "https://github.com/NayanTheSpaceGuy/necronux"

[dependencies]
clap = { version = "4.5.23", features = ["derive", "cargo"] }
clap-verbosity-flag = "3.0.2"
color-eyre = { version = "0.6.3", default-features = false }
flexi_logger = "0.29.8"
log = "0.4.22"
serde = { version = "1.0", features = ["derive"] }
config = "0.15.4"
rpkl = "0.3.5"

[profile.dev.package.backtrace]
# Optimizations for debug builds using color-eyre
opt-level = 3

[profile.release]
debug = false
lto = true
codegen-units = 1
strip = true
incremental = false
