# ==----------------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2024-2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==----------------------------------------------------------------== #

[package]
name = "necronux"
version = "0.4.0-dev"
authors = ["Nayan (NayanTheSpaceGuy) <nayantsg@proton.me>"]
edition = "2024"
rust-version = "1.85.0"
description = "A robust meta-orchestrator for elegantly managing automation tools, scripts, and configurations through an extensible architecture cultivating peace of mind."
readme = "README.md"
homepage = "https://www.necronux.net"
repository = "https://github.com/necronux/necronux"
license = "GPL-3.0-or-later"
keywords = [
  "necronux",
  "automation",
  "configurations",
  "infra",
  "homelab",
  "devops",
  "tools",
  "dotfiles",
]
categories = ["command-line-utilities"]
exclude = [
  ".github/",
  "crates/",
  "gradle/",
  "gradlew",
  "gradlew.bat",
  "tools/",
  "*.gradle.kts",
  "justfile",
]
publish = true
default-run = "necronux"

[workspace]
resolver = "2"
members = ["crates/*"]
[workspace.package]
version = "0.4.0-dev"
authors = ["Nayan (NayanTheSpaceGuy) <nayantsg@proton.me>"]
edition = "2024"
rust-version = "1.85.0"
readme = "README.md"
homepage = "https://www.necronux.net"
repository = "https://github.com/necronux/necronux"
license = "GPL-3.0-or-later"
keywords = [
  "necronux",
  "automation",
  "configurations",
  "infra",
  "homelab",
  "devops",
  "tools",
  "dotfiles",
]
categories = ["command-line-utilities"]
publish = true

[lints.rust]
unsafe_code = "deny"
unused_must_use = "deny"
[workspace.lints.rust]
unsafe_code = "deny"
unused_must_use = "deny"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[profile.release]
debug = false
lto = true
codegen-units = 1
strip = true
incremental = false

[workspace.dependencies]
###################
# DEPS (WORKSPACE)
##################
# Error handling
anyhow = "1.0.98"
# Logging
tracing = { version = "0.1.41", features = [
  "max_level_trace",
  "release_max_level_info",
] }
tracing-log = "0.2.0"
tracing-subscriber = "0.3.19"
# Parsing
rpkl = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
# File system
directories = "6.0.0"
# Cli
clap-verbosity-flag = { version = "3.0.2", default-features = false, features = [
  "tracing",
] }

[dependencies]
######################
# REQUIRED DEPS (BIN)
#####################
# Necronux
necronux_core = { path = "crates/necronux_core", version = "0.4.0-dev", default-features = false }
# Error handling
anyhow = "1.0.98"
# Logging
tracing = { version = "0.1.41", features = [
  "max_level_trace",
  "release_max_level_info",
] }
# Cli
clap = { version = "4.5.37", features = ["derive", "cargo", "deprecated"] }
clap-verbosity-flag = { version = "3.0.2", default-features = false, features = [
  "tracing",
] }
######################
# OPTIONAL DEPS (BIN)
#####################
# Pretty cli
clap-help = { version = "1.4.0", optional = true }
termimad = { version = "0.32.0", optional = true }

[features]
###########
# FEATURES
##########
default = ["schema_v0", "necronux_log", "cli_arg_log"]
experimental = ["experimental_pretty_cli"]
full = ["default", "experimental", "trace"]

# Schema versioned support
schema_v0 = ["necronux_core/schema_v0"]

# Logging support
necronux_log = ["necronux_core/necronux_log"]
# Tracing support
trace = ["necronux_core/trace"]
# Verbosity from cli arg support
cli_arg_log = ["necronux_core/cli_arg_log"]

# Experimental
experimental_pretty_cli = ["dep:termimad", "dep:clap-help"]
