# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: Apache-2.0
# ==-----------------------------------------------------------== #

name: Docs Improvement Request
description: Help us write better docs to catch common issues!
labels: ["A-docs", "C-enhancement", "S-needs-triage"]
assignees:
  - NayanTheSpaceGuy
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a docs improvement request!
  - type: textarea
    attributes:
      label: How can Necronux's documentation be improved?
      description: >
        Provide a link to the documentation and describe how it could be improved. In what ways is it incomplete, incorrect, or misleading?
        If you have suggestions on exactly what the new docs should say, feel free to include them here.
        Alternatively, make the changes yourself and create a pull request instead.
