# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: Apache-2.0
# ==-----------------------------------------------------------== #

name: Feature Request
description: Propose a new feature!
labels: ["C-feature", "S-needs-triage"]
assignees:
  - NayanTheSpaceGuy
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a feature request!
  - type: checkboxes
    attributes:
      label: Please complete the following tasks
      options:
        - label: I have searched the [discussions](https://github.com/NayanTheSpaceGuy/necronux/discussions)
          required: true
        - label: I have searched the [open](https://github.com/NayanTheSpaceGuy/necronux/issues) and [rejected](https://github.com/NayanTheSpaceGuy/necronux/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues
          required: true
  - type: input
    id: version
    attributes:
      label: Necronux Version
      description: >
        Please provide the release number or commit hash of the version you're using.
        PLEASE DO NOT PUT "latest" HERE, use precise version.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve or what need does it fill?
      description: >
        Please provide a description of why this particular feature should be added.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What solution would you like?
      description: >
        Please provide a clear and concise description of what you want to happen for the problem presented.
  - type: textarea
    id: alternatives
    attributes:
      label: What alternative(s) have you considered?
      description: >
        Please provide other solutions to solve and/or work around the problem presented.
  - type: textarea
    id: additionalcontext
    attributes:
      label: Additional context
      description: >
        Please provide any other information you would like to add such as related previous work, screenshots, benchmarks, etc. that might be helpful.
