# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==-----------------------------------------------------------== #

[package]
name = "necronux_core"
authors.workspace = true
edition.workspace = true
rust-version = "1.74.1"
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
color-eyre.workspace = true
flexi_logger.workspace = true
log.workspace = true
rpkl.workspace = true
serde.workspace = true
