# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==-----------------------------------------------------------== #

[package]
name = "necronux_core"
description = "The Necronux Core Library."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
# necronux (required)
necronux_internal = { path = "../necronux_internal", version = "0.4.0-dev", default-features = false }

[features]
default = ["stdschema_v1", "necronux_log", "cli_arg_log", "git"]
full = ["default", "trace"]

# StdSchema Versioned Support
stdschema_v1 = ["necronux_internal/stdschema_v1"]

# Logging support
necronux_log = ["necronux_internal/necronux_log"]

# Tracing support
trace = ["necronux_internal/trace"]

# Verbosity from cli arg support
cli_arg_log = ["necronux_internal/cli_arg_log"]

# VCS (Version Control System) support
# Git support
git = ["necronux_internal/git"]
