# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==-----------------------------------------------------------== #

[package]
name = "necronux_core"
description = "Provides core business logic for Necronux."
version = "0.3.0-rc.1"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
color-eyre.workspace = true
log.workspace = true
rpkl.workspace = true
serde.workspace = true
