# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==-----------------------------------------------------------== #

[package]
name = "necronux_internal"
description = "An internal Necronux crate."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
# necronux
necronux_utils = { path = "../necronux_utils", version = "0.3.0-dev" }
# necronux (optional)
necronux_cli_app = { path = "../necronux_cli_app", version = "0.3.0-dev", optional = true }
necronux_core = { path = "../necronux_core", version = "0.3.0-dev", optional = true }

[features]
necronux_cli_app = ["dep:necronux_cli_app"]

necronux_core = ["dep:necronux_core"]
