# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==-----------------------------------------------------------== #

[package]
name = "necronux_internal"
description = "An internal Necronux crate."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
################
# REQUIRED DEPS
###############
# Necronux
necronux_engine = { path = "../necronux_engine", version = "0.4.0-dev", default-features = false }
necronux_pkg = { path = "../necronux_pkg", version = "0.4.0-dev", default-features = false }
necronux_utils = { path = "../necronux_utils", version = "0.4.0-dev", default-features = false }
################
# OPTIONAL DEPS
###############
# Necronux
necronux_log = { path = "../necronux_log", version = "0.4.0-dev", default-features = false, optional = true }

[features]
###########
# FEATURES
##########
necronux_log = ["dep:necronux_log"]
cli_arg_log = ["necronux_log", "necronux_log/cli_arg_log"]
trace = ["necronux_log", "necronux_engine/trace", "necronux_utils/trace"]

grimoire_schema_v0 = ["necronux_engine/grimoire_schema_v0"]
