# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==-----------------------------------------------------------== #

[package]
name = "necronux_internal"
description = "An internal Necronux crate."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
# necronux (required)
necronux_engine = { path = "../necronux_engine", version = "0.4.0-dev", default-features = false }
necronux_vcs = { path = "../necronux_vcs", version = "0.4.0-dev", default-features = false }
necronux_utils = { path = "../necronux_utils", version = "0.4.0-dev", default-features = false }

# necronux (optional)
necronux_log = { path = "../necronux_log", version = "0.4.0-dev", default-features = false, optional = true }

[features]
necronux_log = ["dep:necronux_log"]

stdschema_v1 = ["necronux_engine/stdschema_v1"]

git = ["necronux_vcs/git"]

trace = [
  "necronux_engine/trace",
  "necronux_vcs/trace",
  "necronux_utils/trace",
  "necronux_log",
]
cli_arg_log = ["necronux_log/cli_arg_log", "necronux_log"]
