# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==-----------------------------------------------------------== #

[package]
name = "necronux_utils"
description = "A collection of utils for Necronux."
version = "0.4.0-dev"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
color-eyre.workspace = true
flexi_logger.workspace = true
log.workspace = true
