# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==-----------------------------------------------------------== #

[package]
name = "necronux_cli_app"
description = "Provides the CLI implementation for Necronux."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
clap-verbosity-flag.workspace = true
color-eyre.workspace = true
flexi_logger.workspace = true
log.workspace = true

necronux_core = { path = "../necronux_core", version = "0.3.0-dev" }
necronux_utils = { path = "../necronux_utils", version = "0.3.0-dev" }
