# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==-----------------------------------------------------------== #

[package]
name = "necronux_log"
description = "Provides logging for Necronux."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
# error handling (required)
anyhow = "1.0.98"
# logging (required)
tracing = { version = "0.1.41", features = [
  "max_level_trace",
  "release_max_level_info",
] }
tracing-log = "0.2.0"
tracing-subscriber = "0.3.19"
# indicatif
tracing-indicatif = "0.3.9"
indicatif = "0.17.11"

# cli arg (optional)
clap-verbosity-flag = { version = "3.0.2", default-features = false, features = [
  "tracing",
], optional = true }

[features]
cli_arg_log = ["dep:clap-verbosity-flag"]
