# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==-----------------------------------------------------------== #

[package]
name = "necronux_engine"
description = "Provides core business logic for Necronux."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
################
# REQUIRED DEPS
###############
# Necronux
necronux_utils = { path = "../necronux_utils", version = "0.4.0-dev", default-features = false }
# Error handling
anyhow = { workspace = true }
# Logging
tracing = { workspace = true }
# Parsing
rpkl = { workspace = true }
serde = { workspace = true }

[features]
###########
# FEATURES
##########
schema_v0 = []

trace = []
