# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later
# ==-----------------------------------------------------------== #

[package]
name = "necronux_engine"
description = "Provides core business logic for Necronux."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
# necronux (required)
necronux_utils = { path = "../necronux_utils", version = "0.4.0-dev", default-features = false }

# error handling (required)
anyhow = "1.0.98"
# logging (required)
tracing = { version = "0.1.41", features = [
  "max_level_trace",
  "release_max_level_info",
] }
# parsing (required)
rpkl = "0.4.2"
serde = { version = "1.0.219", features = ["derive"] }

[features]
stdschema_v1 = []

trace = []
